learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path(r'^users/', include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path

from . import views

urlpatterns = [
    # Home page
    path(r'', views.index, name='index'),
    path(r'^topics/$', views.topics, name='topics'),

    path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    path(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing an entry
    path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    path(r'^car_brands/$', views.car_brands, name='car_brands'),

    path(r'^car_brands/(?P<brand_id>\d+)/$', views.brand, name='brand'),

    path(r'^new_brand/$', views.new_brand, name='new_brand'),

    # Page for adding a new entry
    path(r'^new_car/(?P<brand_id>\d+)/$', views.new_car, name='new_car'),

    # Page for editing an entry
    path(r'^edit_car/(?P<car_id>\d+)/$', views.edit_car, name='edit_car'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from users import views

urlpatterns = [
    path(r'login/$', LoginView.as_view(template_name='users/login.html'), name="login"),
    path(r'^logout/$', views.logout_view, name='logout'),

    path(r'^signup/$', views.signup, name='signup'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
]

learning_logs/models.py
from django.db import models


# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""

        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."


class CarBrands(models.Model):
    """A topic the user is learning about"""
    description = models.CharField(max_length=200)
    brand_foundation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""

        return self.description


class Car(models.Model):
    """Something specific learned about a topic"""
    brand = models.ForeignKey(CarBrands, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

learning_logs/forms.py
from django import forms
from .models import Topic, Entry, CarBrands, Car


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrands
        fields = ['description']
        labels = {'description': ''}


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 90})}

learning_logs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import TopicForm, EntryForm, CarBrandForm, CarForm
from .models import Topic, Entry, CarBrands, Car
from django.urls import reverse


def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Show all topics."""
    t = Topic.objects.order_by('date_added')
    context = {'topics': t}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    t = Topic.objects.get(id=topic_id)
    entries = t.entry_set.order_by('-date_added')
    context = {'topic': t, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    t = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_e = form.save(commit=False)
            new_e.topic = t
            new_e.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': t, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    t = entry.topic
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[t.id]))
    context = {'entry': entry, 'topic': t, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def car_brands(request):
    """Show all topics."""
    t = CarBrands.objects.order_by('brand_foundation_date')
    context = {'brands': t}
    return render(request, 'learning_logs/brands.html', context)


def brand(request, brand_id):
    """Show a single topic and all its entries."""
    b = CarBrands.objects.get(id=brand_id)
    cars = b.car_set.order_by('-date_added')
    context = {'brand': b, 'cars': cars}
    return render(request, 'learning_logs/brand.html', context)


def new_brand(request):
    """Add a new brand."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CarBrandForm()
    else:
        # POST data submitted; process data.
        form = CarBrandForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:car_brands'))
    context = {'form': form}
    return render(request, 'learning_logs/new_brand.html', context)


def new_car(request, brand_id):
    """Add a new car for a particular brand."""
    b = CarBrands.objects.get(id=brand_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CarForm()
    else:
        # POST data submitted; process data.
        form = CarForm(data=request.POST)
        if form.is_valid():
            new_c = form.save(commit=False)
            new_c.brand = b
            new_c.save()
            return HttpResponseRedirect(reverse('learning_logs:brand', args=[brand_id]))
    context = {'brand': b, 'form': form}
    return render(request, 'learning_logs/new_car.html', context)


def edit_car(request, car_id):
    """Edit an existing car."""
    car = Car.objects.get(id=car_id)
    b = car.brand
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = CarForm(instance=car)
    else:
        # POST data submitted; process data.
        form = CarForm(instance=car, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:brand', args=[b.id]))
    context = {'car': car, 'brand': b, 'form': form}
    return render(request, 'learning_logs/edit_car.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    <a href="{% url 'learning_logs:car_brands' %}">Car Brands</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:signup' %}">signup</a> -
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/brand.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Brand: {{ brand }}</p>
<p>Cars:</p>
    <p>
        <a href="{% url 'learning_logs:new_car' brand.id %}">add new Car</a>
      </p>
  <ul>
{% for car in cars %}
  <li>
    <p>{{ car.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ car.text|linebreaks }}</p>
    <p>
      <a href="{% url 'learning_logs:edit_car' car.id %}">edit car</a>
    </p>
  </li>
   {% empty %}
  <li>
   There are no cars for this brand yet.
  </li>
{% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/brands.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>brands</p>
 <ul>
   {% for brand in brands %}
    <li>
        <a href="{% url 'learning_logs:brand' brand.id %}">{{ brand }}</a>
    </li>
     {% empty %}
    <li>No brands have been added yet.</li>
   {% endfor %}
 </ul>
    <a href="{% url 'learning_logs:new_brand' %}">Add a new brand:</a>
{% endblock content %}

learning_logs/templates/learning_logs/edit_car.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:brand' brand.id %}">{{ brand }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_car' car.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">save changes</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">save changes</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_brand.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Add a new brand:</p>
<form action="{% url 'learning_logs:new_brand' %}" method='post'>
   {% csrf_token %}
  {{ form.as_p }}
 <button name="submit">add brand</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_car.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:brand' brand.id %}">{{ brand }}</a></p>
<p>Add a new car:</p>
<form action="{% url 'learning_logs:new_car' brand.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name='submit'>add car</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name='submit'>add entry</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
   {% csrf_token %}
  {{ form.as_p }}
 <button name="submit">add topic</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Topic: {{ topic }}</p>
<p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
      </p>
  <ul>
{% for entry in entries %}
  <li>
    <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ entry.text|linebreaks }}</p>
    <p>
      <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
    </p>
  </li>
   {% empty %}
  <li>
   There are no entries for this topic yet.
  </li>
{% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Topics</p>
 <ul>
   {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
     {% empty %}
    <li>No topics have been added yet.</li>
   {% endfor %}
 </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}